import { AssetType, type OrchestratorContract } from "../types/contracts.js";

export const orchestratorContracts: readonly OrchestratorContract[] = [
	{
		id: "specflow-advance-bundle",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-advance-bundle",
		entryModule: "dist/bin/specflow-advance-bundle.js",
		stdoutSchemaId: "advance-bundle-result",
		references: [],
	},
	{
		id: "specflow-analyze",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-analyze",
		entryModule: "dist/bin/specflow-analyze.js",
		stdoutSchemaId: "analyze-project",
		references: [],
	},
	{
		id: "specflow-create-sub-issues",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-create-sub-issues",
		entryModule: "dist/bin/specflow-create-sub-issues.js",
		stdinSchemaId: "create-sub-issues-input",
		stdoutSchemaId: "create-sub-issues-result",
		references: [],
	},
	{
		id: "specflow-design-artifacts",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-design-artifacts",
		entryModule: "dist/bin/specflow-design-artifacts.js",
		stdoutSchemaId: "design-artifact-next",
		references: [],
	},
	{
		id: "specflow-fetch-issue",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-fetch-issue",
		entryModule: "dist/bin/specflow-fetch-issue.js",
		stdoutSchemaId: "issue-metadata",
		references: [],
	},
	{
		id: "specflow-filter-diff",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-filter-diff",
		entryModule: "dist/bin/specflow-filter-diff.js",
		stderrSchemaId: "diff-summary",
		references: [],
	},
	{
		id: "specflow-init",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-init",
		entryModule: "dist/bin/specflow-init.js",
		stdoutSchemaId: "init-project",
		references: [],
	},
	{
		id: "specflow-install",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-install",
		entryModule: "dist/bin/specflow-install.js",
		references: [],
	},
	{
		id: "specflow-launch-watch",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-launch-watch",
		entryModule: "dist/bin/specflow-launch-watch.js",
		// stdout is a human-readable `WATCH_METHOD=<method>` line plus an
		// optional Japanese hint on manual fallback — not a JSON envelope.
		references: [],
	},
	{
		id: "specflow-prepare-change",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-prepare-change",
		entryModule: "dist/bin/specflow-prepare-change.js",
		stdoutSchemaId: "run-state",
		references: [],
	},
	{
		id: "specflow-review-apply",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-review-apply",
		entryModule: "dist/bin/specflow-review-apply.js",
		stdoutSchemaId: "review-apply-result",
		references: [
			"prompt:review_apply_prompt",
			"prompt:review_apply_rereview_prompt",
		],
	},
	{
		id: "specflow-challenge-proposal",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-challenge-proposal",
		entryModule: "dist/bin/specflow-challenge-proposal.js",
		stdoutSchemaId: "challenge-proposal-result",
		references: ["prompt:challenge_proposal_prompt"],
	},
	{
		id: "specflow-generate-task-graph",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-generate-task-graph",
		entryModule: "dist/bin/specflow-generate-task-graph.js",
		stdoutSchemaId: "generate-task-graph-result",
		references: [],
	},
	{
		id: "specflow-review-design",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-review-design",
		entryModule: "dist/bin/specflow-review-design.js",
		stdoutSchemaId: "review-design-result",
		references: [
			"prompt:review_design_prompt",
			"prompt:review_design_rereview_prompt",
			"prompt:fix_design_prompt",
		],
	},
	{
		id: "specflow-migrate-records",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-migrate-records",
		entryModule: "dist/bin/specflow-migrate-records.js",
		references: [],
	},
	{
		id: "specflow-run",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-run",
		entryModule: "dist/bin/specflow-run.js",
		stdoutSchemaId: "run-state",
		references: [],
	},
	{
		id: "specflow-spec-verify",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-spec-verify",
		entryModule: "dist/bin/specflow-spec-verify.js",
		stdoutSchemaId: "spec-verify-result",
		references: [],
	},
	{
		id: "specflow-watch",
		type: AssetType.Orchestrator,
		filePath: "bin/specflow-watch",
		entryModule: "dist/bin/specflow-watch.js",
		// Real-time TUI adapter: stdout is ANSI-rendered frames, not a
		// structured JSON envelope, so no stdoutSchemaId applies.
		references: [],
	},
];
